version: '3'
services:
  db:
    image: postgres
    container_name: interview-sched-db
    networks:
      - app-bridge
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: vferreira_admin
      POSTGRES_DB: interview_sched

  api:
    image: vrfvitor/interview-sched
    container_name: interview-sched-api
    networks:
      - app-bridge
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      DB_HOST: interview-sched-db

networks:
  app-bridge:
    driver: bridge